### ISSUE TITLE
How can I apply gradient color for both light and dark mode?

### ISSUE THREAD

**Issue by haodev007** [justin-chu/react-fast-marquee#78]
Hi everyone,

I would love to apply gradient color for light and dark mode respectively. But I dont know how to do.

Here is my code snippet.
```bash
<Marquee
      autoFill
      pauseOnHover
      gradient={true}
      gradientColor={[0, 0, 0]}
      gradientWidth={80}
      speed={30}
>
// images
</Marquee>
````

Here is screenshot for dark mode. :)
![image](https://github.com/justin-chu/react-fast-marquee/assets/98631674/12910bf5-bbca-44c0-8b20-b686be213e0d)

Here is screenshot for light mode. :(
![image](https://github.com/justin-chu/react-fast-marquee/assets/98631674/95f9d9f4-ee4f-4047-b895-434a227a3e81)

Please givmme good idea and suggestion. Thanks in advance!

**Comment by mh-jsx** [comment]
It depends on how you handle your theme, are you using some kinda context for switching themes. 
You can dynamically change the gradient color value conditionally. 

const {theme} = useThemeContext()

<Marquee
      autoFill
      pauseOnHover
      gradient={true}
      gradientColor={theme === "light" ?  [0, 0, 0] : [255, 255, 255]}
      gradientWidth={80}
      speed={30}
>
</Marquee>

Can you tell how you handle your theme.

**Comment by haodev007** [comment]
Yes, you're right. I already handled it like your way lol.
I think I can close this issue as completed. Thanks for your reply @mh-jsx !

**Comment by junwen-k** [comment]
It seems like setting just using `mask` css property will make it work across both dark / light theme based on this [Codepen](https://codepen.io/kevinpowell/pen/BavVLra) by Kevin Powell.

```css
.scroller[data-animated="true"] {
  overflow: hidden;
  -webkit-mask: linear-gradient(
    90deg,
    transparent,
    white 20%,
    white 80%,
    transparent
  );
  mask: linear-gradient(90deg, transparent, white 20%, white 80%, transparent);
}
```

I am using Tailwind CSS and I am able to implement the gradient using this class name.

```tsx
className="[mask:linear-gradient(90deg,_transparent,_white_20%,_white_80%,_transparent)]"
```

@justin-chu Do you want to consider implementing the gradient with this approach so that we don't have to explicitly set the gradient color? :)
